# .readthedocs.yaml
# Read the Docs configuration file
# See: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2  # Required

# Documentation formats to build and make available
formats:
  - pdf
  - epub

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"  # Use standard CPython version; `mambaforge-22.9` is not valid here

# Python-related configuration
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
