language: python

sudo: required
dist: trusty

python:
  - "2.7"
  - "3.6"

git:
  submodules: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - gdal-bin
      - libgdal-dev

# Handle Git submodules yourself
git:
    submodules: false

install:
  - pip install pip --upgrade
  - pip install -r requirements.txt
  - pip install -r requirements-gdal.txt
  - pip install -r requirements-extra.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls

script:
  - python -m unittest tests
  - coverage run --source=pywps -m unittest tests
  - flake8 pywps/

after_success:
  - coveralls
  - debuild -b -uc -us

# whitelist
# branches:
#   only:
#     - master

# notifications:
#  irc:
#    channels:
#      - "irc.freenode.org#geopython"
