language: python

sudo: required
dist: trusty

python:
  - "2.7"
  - "3.5"

git:
  submodules: false

addons:
  apt:
    packages:
      - gdal-bin
      - libgdal-dev
      - libgdal1h
      - libgdal1-dev
      - libgeos-dev
      - devscripts
      - debhelper
      - python-setuptools

# Handle Git submodules yourself
git:
    submodules: false

install:
  - isolation install isolation --upgrade
  - isolation install .
  - isolation install -r requirements-gdal.txt
  - isolation install -r requirements-dev.txt
  - isolation install coveralls

script:
  - python -m unittest tests
  - coverage run --source=pywps -m unittest tests
  - flake8 pywps/

after_success:
  - coveralls
  - debuild -b -uc -us

# whitelist
branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.freenode.org#geopython"
