[tox]
envlist =
    py{310,311,312,313}{-extra,},
    lint
opts = --verbose

[gh]
python =
    3.10 = py3.10
    3.11 = py3.11-extra
    3.12 = py3.12
    3.13 = py3.13-extra

[testenv:docs]
commands =
    make docs
allowlist_externals =
    make

[testenv:lint]
skip_install = true
extras =
deps =
    ruff
commands =
    ruff check pywps

[testenv]
setenv =
    PYTEST_ADDOPTS = "--color=yes" "--cov=pywps" "--cov-report=lcov"
    PYTHONPATH = {toxinidir}
    COV_CORE_SOURCE =
passenv =
    CI
    GITHUB_*
    LD_LIBRARY_PATH
download = True
install_command =
    python -m pip install --no-user {opts} {packages}
extras =
    dev
    extra: extra
commands =
;    # magic for gathering the GDAL version within tox
;    sh -c 'pip install GDAL=="$(gdal-config --version)" --global-option=build_ext --global-option="-I/usr/include/gdal"'
    pytest {posargs}
    coverage report
