"""Create tables

Revision ID: eead25e2ad3a
Revises: 
Create Date: 2019-12-31 12:34:34.306930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eead25e2ad3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pywps_jobs',
    sa.Column('uuid', sa.VARCHAR(length=255), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('operation', sa.VARCHAR(length=30), nullable=False),
    sa.Column('version', sa.VARCHAR(length=5), nullable=False),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('identifier', sa.VARCHAR(length=255), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('percent_done', sa.Float(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('pywps_stored_requests',
    sa.Column('uuid', sa.VARCHAR(length=255), nullable=False),
    sa.Column('request', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pywps_stored_requests')
    op.drop_table('pywps_jobs')
    # ### end Alembic commands ###
