name: build ⚙️

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_SERVICE_NAME: github
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
        sudo apt-get update && sudo apt-get -y install libnetcdf-dev libhdf5-dev
    - uses: actions/setup-python@v2
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements 📦
      run: |
        pip3 install pip --upgrade
        pip3 install -r requirements.txt
        pip3 install -r requirements-dev.txt
        pip3 install -r requirements-extra.txt
    - name: run tests ⚙️
      run: pytest -v tests
    - name: run coveralls ⚙️
      run: coveralls
      if: matrix.python-version == 3.7
    - name: build docs 🏗️
      run: |
        pip3 install -e .
        cd docs && make html
      if: matrix.python-version == 3.7
    - name: run flake8 ⚙️
      run: flake8 pywps
      if: matrix.python-version == 3.7
